version: '3.8'


networks:
  kong-net:
    name: kong-net
    driver: bridge

services: 
  ms-user:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: 'ms-management-user'
    ports: 
      - 3333:3333
    expose: 
      - 3333
    networks:
      - kong-net


